""""""""""""""""""""""""""""""""""""""""
" CLAUDE'S RECOS FOR XDG COMPATIBILITY
""""""""""""""""""""""""""""""""""""""""

set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after

set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after

let g:netrw_home = $XDG_DATA_HOME . "/vim"
call mkdir($XDG_DATA_HOME."/vim/spell", 'p')

set backupdir=$XDG_STATE_HOME/vim/backup | call mkdir(&backupdir, 'p')
set directory=$XDG_STATE_HOME/vim/swap   | call mkdir(&directory, 'p')
set undodir=$XDG_STATE_HOME/vim/undo     | call mkdir(&undodir,   'p')
set viewdir=$XDG_STATE_HOME/vim/view     | call mkdir(&viewdir,   'p')

set viminfofile=$XDG_STATE_HOME/vim/viminfo

""""""""""""""""""
" BASIC
""""""""""""""""""
syntax on
filetype indent plugin on "plugin on is necessary for vimwiki
set smartindent
set shiftwidth=4
set expandtab "tabs = spaces
set tabstop=4 "show
set undofile
set undodir=~/.vim/undo

"""""""""""""""""""""""""""""
"MISCELLANOUS
"""""""""""""""""""""""""""""
set hidden
set number relativenumber "show line number
set wildmenu "visual autocomplete for cmd menu
set showmatch "highlight {([
set clipboard=unnamed "use + as system clipboard register
set nocompatible
set spelllang=fr,en
set spellfile=~/.vim/spell/fr.utf-8.add
set incsearch "search as characters are entered 
set hlsearch "higlight matches
let mapleader=" "
"""""""""""""""""""""""""""""
"AUTOCMD
"""""""""""""""""""""""""""""
autocmd InsertEnter  *.{markdown,md} set conceallevel=0
autocmd InsertLeave  *.{markdown,md} set conceallevel=2
autocmd BufRead,BufNewFile *.conf setfiletype dosini
""""""""""""""""""""""""""""""
"NAVIGATION
""""""""""""""""""""""""""""""
noremap <C-J> :bnext<CR>
noremap <C-K> :bprev<CR>

"""""""""""""""""""""""""""""
"MAPPING
"""""""""""""""""""""""""""""
nnoremap <space> <leader>
nnoremap <leader><leader> za
nnoremap zz :update<CR>
"nnoremap <C-P> :ls<CR>:b<Space>
"nnoremap <F5> i#<Space><C-r>=system('date +%F')<CR><CR>
"inoremap <F8> <Esc>:update<CR> :!make<CR><CR><CR>
"nnoremap <F9> :update<CR> :!make<CR><CR><CR>
"nnoremap <F11> :! python3 %<CR>
"nnoremap <F12> :update<CR> :!pdflatex %<CR><CR><CR> :! evince $(echo % \|sed 's/tex$/pdf/') & disown<CR><CR>
"nnoremap <leader>m :! make<CR><CR><CR>

"""""""""""""""""""""""""""""
""""""" addons
"""""""""""""""""""""""""""""
let g:Tex_MultipleCompileFormats='pdf,bibtex,pdf'
let $BASH_ENV = "~/.bash_aliases"
"""""""""""""""""""""""""""""

""""PLUGINS"""""""""""
""""curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
"""":PlugInstall 
"""""""""""""""""""""""""""""
call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex'
Plug 'lervag/wiki.vim'
Plug 'ap/vim-css-color'
Plug 'francoiscabrol/ranger.vim'
Plug 'dhruvasagar/vim-open-url'
Plug 'dhruvasagar/vim-table-mode'
Plug 'chrisbra/vim-diff-enhanced'
"Plug 'RRethy/vim-hexokinase'
call plug#end()

"""""""""""""""""""""""""""""
"" VIMWIKI"""""""""""""""""""
"""""""""""""""""""""""""""""
let g:wiki_root = '~/notes'
let g:wiki_filetypes = ['md']
let g:wiki_link_extension = '.md'
let g:wiki_link_target_type = 'md'
let g:wiki_write_on_nav = 1
let g:wiki_zotero_root = '~/data/zotero'
"""""""""""""""""""""""""""""
"""" VIM PANDOC""""""""""""""
"""""""""""""""""""""""""""""
let g:pandoc#biblio#sources='l'
let g:pandoc#completion#bib#mode='citeproc'

"""""""""""""""""""""""""""""
"""""""""" APPEARANCE
"""""""""""""""""""""""""""""
"set laststatus=2
