#!/bin/sh

# ~/.aliases
#
# COMMON ALIASES AND FUNCTIONS FOR ALL SHELLS

# Switching shells

alias wlqt='qtile start -b wayland'

alias t='task'
alias fucking-pipewire='systemctl --user restart pipewire.service'
alias fucking-qtile='qtile cmd-obj -o cmd -f reload_config'
alias restart-qtile='qtile cmd-obj -o cmd -f restart'
alias poweroff='sudo systemctl poweroff'
alias reboot='sudo systemctl reboot'
alias suspend='sudo systemctl suspend'
alias p44='pw-metadata -n settings 0 clock.force-rate 44100'
alias p48='pw-metadata -n settings 0 clock.force-rate 48000'
alias batterie='upower -i /org/freedesktop/UPower/devices/battery_BAT1'
alias kdr='sudo keyd reload'
alias loadenv="source $HOME/.environment"
alias v='NVIM_APPNAME=lazyvim nvim'

alias ß="interactive_git_sync.sh"
alias s="script_launcher.sh --embedded"
alias cfg="edit_chezmoi_cfg_files.sh"
alias ú="paru -Syu --noconfirm --nouseask"
alias ¶="pacman-fuzzy-search.sh"
alias pacfzf="pacman-fuzzy-search.sh"
alias f='fzf-file-manager.sh'
alias ns="new_script_creator.sh"
alias e='editor.sh'
alias fe='editor.sh'

alias l=eza
alias l1='eza --oneline'
alias ll='eza -l --icons=auto'
alias la='eza -la --icons=auto'
alias r='ranger'
alias ai='aichat'
alias nv='nvim'
alias ×='chmod +x'
alias cx='chmod +x'
alias kdr='sudo keyd reload'

# TMUX
alias tm='tmux_manager.py'
alias tt='tmux attach -t DEFAULT'
alias ta='tmux attach'
alias ts='tmux new -s'
alias tl='tmux ls'
alias tf='tmux_fzf'
tmux_fzf() {
    tmux attach -t "$(tmux ls | cut -d: -f1 | fzf --select-1 --height=~100%)"
}

espp() {
    [[ ! -f '/opt/esp-idf/export.sh' ]] && /opt/esp-idf/install.sh
    /opt/esp-idf/export.sh
    }
alias serv="list_process.sh"

#aliases['cpu-max'] = 'tuned-adm profile latency-performance'
#aliases['cpu-balanced'] = 'tuned-adm profile balanced'
#aliases['cpu-min'] = 'tuned-adm profile laptop-battery-powersave'
#aliases['lobechat'] = 'docker run -p 3210:3210 f7e1581b25a3'

alias update_mirrors='sudo reflector --sort rate --country France,Germany,USA --protocol https --latest 30 --save /etc/pacman.d/mirrorlist'

# core not in system comm -23 <(pacman -Slq core | sort) <(pacman -Qq | sort)
alias ip_livebox="curl -4 -s ifconfig.me"

O() {
    source "$(fd 'activate$' -I -H | fzf --select-1 --height=~100%)"
}
X() {
    deactivate
}
alias skb="setxkbmap us altgr-intl"

check_new_env () {
    comm -13 \
        <(env | cut -d= -f1 | sort) \
        <(cat "$XDG_CONFIG_HOME"/environment.d/* | cut -d= -f1 | sort) |
        grep -vP '#|^$'
    }

convert_env_dir() { 
    cat "$XDG_CONFIG_HOME"/environment.d/* | rg '=' | sed -E 's/^(.*=)/export \1/'
}
