#!/bin/sh

# ~/.aliases
#
# COMMON ALIASES AND FUNCTIONS FOR ALL SHELLS

# Switching shells
alias »="shell_change"
alias r-pipewire='systemctl --user restart pipewire.service'
alias r-load-qtile='qtile cmd-obj -o cmd -f reload_config'
alias r-start-qtile='qtile cmd-obj -o cmd -f restart'
alias poweroff='sudo systemctl poweroff'
alias reboot='sudo systemctl reboot'
alias suspend='sudo systemctl suspend'
alias p44='pw-metadata -n settings 0 clock.force-rate 44100'
alias p48='pw-metadata -n settings 0 clock.force-rate 48000'
alias batterie='upower -i /org/freedesktop/UPower/devices/battery_BAT1'
alias kdr='sudo keyd reload'

alias Ð="cd $HOME/Desktop/"
alias ©="cd $CHEZMOI && git status -vv"
alias ß="cd $SCRIPTS && git status -vv"
alias ð="cd $LOCALDATA && git status -vv"
alias þ="cd $PSYRIS && git status -vv"
alias s©="sync-repo.sh $CHEZMOI && chezmoi apply && sudo keyd reload && chezmoi status -vv"
alias sß="sync-repo.sh $SCRIPTS && utils_update_symlinks.sh"
alias sð="sync-repo.sh $LOCALDATA"
alias sþ="sync-repo.sh $PSYRIS"

alias s="script_launcher.sh --embedded"
alias cfg="edit_chezmoi_cfg_files.sh"
alias ¶="pacman-fuzzy-search.sh"
alias f='fzf-file-manager.sh'
alias ns="new_script_creator.sh"
alias e='editor.sh'

alias l=eza
alias li='eza --oneline'
alias ll='eza -l --icons=auto'
alias la='eza -la --icons=auto'
alias r='ranger'
alias ai='aichat'
alias nv='nvim'
alias cx='chmod +x'
alias kd='sudo keyd reload'

# TMUX
alias ta='tmux attach'
alias ts='tmux new -s'
alias tl='tmux ls'
alias tf='tmux_fzf'
tmux_fzf() {
    tmux attach -t "$(tmux ls | cut -d: -f1 | fzf --select-1 --height=~100%)"
}

alias serv="bat $(which list_process.sh); list_process.sh"

#aliases['cpu-max'] = 'tuned-adm profile latency-performance'
#aliases['cpu-balanced'] = 'tuned-adm profile balanced'
#aliases['cpu-min'] = 'tuned-adm profile laptop-battery-powersave'
#aliases['lobechat'] = 'docker run -p 3210:3210 f7e1581b25a3'

alias update_mirrors='sudo reflector --sort rate --country France,Germany,USA --protocol https --latest 150 --save /etc/pacman.d/mirrorlist'

# core not in system comm -23 <(pacman -Slq core | sort) <(pacman -Qq | sort)
alias ip_livebox="curl -4 -s ifconfig.me"

# FUNCTIONS
shell_change() {
    eval "$(chsh -l | fzf --select-1 --height=~100% -q "$1")"
}

_() {
    last_cmd="$(fc -ln -1)"
    if [ -z "$1" ]; then
        echo "$last_cmd" | "$@"
    else
        echo "$last_cmd"
    fi

}

O() {
    source "$(fd 'activate$' -I | fzf --select-1 --height=~100%)"
}
X() {
    deactivate
}
##      shopt -s expand_aliases
##
##      # ALIASES ####################################################################
##
##      alias ls='ls --color=auto'
##      alias grep='grep --color=auto'
##      alias fgrep='fgrep --color=auto'
##      alias egrep='egrep --color=auto'
##
##
##      # own apps
##      # alias biovector='cd /home/matias/code/biovector/biovector && python3 main.py'
##      # alias bv='biovector'
##
##      # apps
##      alias p=python3
##
##      # two letter app
##
##      # bib files
##      alias bib='vim ~/data/bib/standard.bib'
##      alias bbb='vim ~/data/bib/bibliotheque.bib'
