#!/bin/sh

# ~/.aliases
#
# COMMON ALIASES FOR ALL SHELLS

# Switching shells
#alias _xsh="sudo chsh -s $(which xonsh) $(whoami)"
#alias _zsh="sudo chsh -s $(which zsh) $(whoami)"
#alias _bsh="sudo chsh -s $(which bash) $(whoami)"

alias cfg="edit_chezmoi_cfg_files.sh"
alias cð="cd $HOME/Desktop/"
alias ð="$HOME/Desktop"
#alias local_data_stow="stow --dir=$HOME/Dropbox/local_appdata --target=$HOME"

alias fuckingpipe='systemctl --user restart pipewire.service'
alias fuckingtile='qtile cmd-obj -o cmd -f reload_config'
alias poweroff='sudo systemctl poweroff'
alias reboot='sudo systemctl reboot'
alias suspend='sudo systemctl suspend'
alias p44='pw-metadata -n settings 0 clock.force-rate 44100'
alias p48='pw-metadata -n settings 0 clock.force-rate 48000'
alias batterie='upower -i /org/freedesktop/UPower/devices/battery_BAT1'

#alias f=fzf
alias e='editor.sh'
alias r='ranger'
alias ai='aichat'
alias nv='nvim'
# TMUX
alias ta='tmux attach'
alias ts='tmux new -s'
#alias tac='tmux attach -t music:cmus'

alias serv='echo "script: list_process.sh"; list_process.sh'

alias s='eza -l $HOME/.scripts'
#alias xxx='conda deactivate'
#alias ooo='conda activate base'

#aliases['cpu-max'] = 'tuned-adm profile latency-performance'
#aliases['cpu-balanced'] = 'tuned-adm profile balanced'
#aliases['cpu-min'] = 'tuned-adm profile laptop-battery-powersave'
#aliases['lobechat'] = 'docker run -p 3210:3210 f7e1581b25a3'
################################
# Maybe useful for zsh or bash
#alias ls='ls --color=auto'
#alias grep='grep --color=auto'
alias update_mirrors='sudo reflector --sort rate --country France,Germany,USA --protocol https --latest 150 --save /etc/pacman.d/mirrorlist'
alias git_sync='sync-repo.sh'
alias git_clone='git_clone_by_author-repo.sh'

# core not in system comm -23 <(pacman -Slq core | sort) <(pacman -Qq | sort)
alias ip_livebox="curl -4 -s ifconfig.me"

# FUNCTIONS

_sgpt() {
	last_cmd="$(fc -ln -1)"
	echo "$last_cmd" | sgpt "$@"
}
##      shopt -s expand_aliases
##
##      # ALIASES ####################################################################
##
##      alias ls='ls --color=auto'
##      alias grep='grep --color=auto'
##      alias fgrep='fgrep --color=auto'
##      alias egrep='egrep --color=auto'
##
##
##      # own apps
##      # alias biovector='cd /home/matias/code/biovector/biovector && python3 main.py'
##      # alias bv='biovector'
##
##      # apps
##      alias p=python3
##
##      # two letter app
##
##      # bib files
##      alias bib='vim ~/data/bib/standard.bib'
##      alias bbb='vim ~/data/bib/bibliotheque.bib'
