windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAAAAAAHAAABVUAAAL/AAAAAAAAABwAAAVVAAAC/wAAAAAAAAAABVYAAAAAAAAA
    HAAABVUAAAL/
  tabs:
  - active: true
    history:
    - last_visited: '2024-06-23T15:59:20'
      original-url: https://www.wikipedia.com/
      pinned: false
      title: Wikipedia
      url: https://www.wikipedia.org/
    - last_visited: '2024-06-23T15:59:40'
      pinned: false
      title: qutebrowser help
      url: qute://help/index.html
    - active: true
      last_visited: '2024-06-23T15:59:45'
      pinned: false
      scroll-pos:
        x: 0
        y: 909
      title: Configuring qutebrowser
      url: qute://help/configuring.html
      zoom: 1.0
